### ISSUE TITLE
wHeRe'S hErMiTcRaFt !?

### ISSUE THREAD

**Issue by JoelZBub** [generikb/Forge-Course-1.18.1#1]
this mod crashes because genericB is trying to take steal your money and he is not going to get on hermitcraft agian bexause docm said so and you shoiouldn't buy this mond or install it ever because it is not even for 1.7.10 wich is the best minecarft ever and judd will never get clout even tho Attak of the B Team was the best modpack and i heard that BDouble0 isn'te even his friend anymore because of how much money judd took from little kids and bdoubz doesn't want to be part of that lying and stealer and that's why he's on hermitcarft and genric isn't just look at the dead youtube and you will see the truth so don 't download this mod or install it or whatever and you won't supporting him or giving your money to terrorists and using charities to hid your money from taxes

**Comment by generikb** [comment]
grain an mambo payed me $1200 USD to not play
